# Site settings
title: Emory Libraries Style Guide
email: lauren.hamel@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  A style guide for Emory Libraries
baseurl: "/styleguide" # the subpath of your site, e.g. /blog
url: "http://template.library.emory.edu" # the base hostname & protocol for your site
github_username:  emory-libraries

exclude: [_includes/patterns]

# Build settings
markdown: kramdown

sass:
  sass_dir: _scss
  
kramdown:
  input: GFM
  hard_wrap: false
  html_to_native: true

# Define dependencies
plugins:
  - jekyll-last-modified-at
  - jekyll-titleize