# Site settings
title: Emory Libraries Style Guide
email: brad@bradfrost.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  emory-libraries

# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  
# Define dependencies
plugins:
  - jekyll-last-modified-at